version: '3.8'

services:
  backend:
    platform: linux/amd64
    build:
      context: ./chatnalyxer-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - OTP_SERVICE_URL=http://admin-dashboard:3001
      - SESSION_MANAGER_URL=http://session-manager:3002
    env_file:
      - ./chatnalyxer-backend/.env
    restart: always

  session-manager:
    build:
      context: ./user-whatsapp-sessions
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    env_file:
      - ./user-whatsapp-sessions/.env
    restart: always

  admin-dashboard:
    build:
      context: ./admin-whatsapp-otp
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./admin-whatsapp-otp/.env
    restart: always

  mobile-web:
    build:
      context: ./chatnalyxer-mobile
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    restart: always
